name: Qodana Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Qodana
        uses: JetBrains/qodana-action@latest
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
